package com.github.teamcalendar.domain;
// Generated 24-Nov-2015 12:56:54 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserResetPassword generated by hbm2java
 */
@Entity
@Table(name = "USER_RESET_PASSWORD", schema = "PUBLIC", catalog = "PUBLIC", uniqueConstraints = @UniqueConstraint(columnNames = "USER_ID") )
public class UserResetPasswordEntity implements Serializable
{

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer           id;
    private UserEntity        user_id;
    private String            resetUuid;

    public UserResetPasswordEntity()
    {
    }

    public UserResetPasswordEntity(UserEntity user, String resetUuid)
    {
        this.user_id = user;
        this.resetUuid = resetUuid;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId()
    {
        return this.id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_ID", unique = true, nullable = false)
    public UserEntity getUser_id()
    {
        return this.user_id;
    }

    public void setUser_id(UserEntity user)
    {
        this.user_id = user;
    }

    @Column(name = "RESET_UUID", nullable = false, length = 36)
    public String getResetUuid()
    {
        return this.resetUuid;
    }

    public void setResetUuid(String resetUuid)
    {
        this.resetUuid = resetUuid;
    }

}
