package com.github.teamcalendar.domain;
// Generated 22-Nov-2015 15:47:07 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserResetPassword generated by hbm2java
 */
@Entity
@Table(name = "USER_RESET_PASSWORD")
public class UserResetPassword implements Serializable
{

    private Integer    id;
    private UserEntity user;
    private String     resetUuid;

    public UserResetPassword()
    {
    }

    public UserResetPassword(UserEntity user, String resetUuid)
    {
        this.user = user;
        this.resetUuid = resetUuid;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId()
    {
        return this.id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_ID", nullable = false)
    public UserEntity getUser()
    {
        return this.user;
    }

    public void setUser(UserEntity user)
    {
        this.user = user;
    }

    @Column(name = "RESET_UUID", nullable = false, length = 36)
    public String getResetUuid()
    {
        return this.resetUuid;
    }

    public void setResetUuid(String resetUuid)
    {
        this.resetUuid = resetUuid;
    }

}
